INSERT INTO symptoms (id, description) VALUES
(1, 'I have trouble concentrating or keeping focus.'),
(2, 'I feel sad or down most of the day, nearly every day.'),
(3, 'I have lost interest in activities I used to enjoy.'),
(4, 'I feel hopeless about the future.'),
(5, 'I feel excessive guilt or blame myself a lot.'),
(6, 'I often think about death or suicide.'),
(7, 'I feel anxious or worried most of the time.'),
(8, 'I have sudden episodes of intense fear or panic.'),
(9, 'I avoid certain places or situations because I fear they will make me anxious.'),
(10, 'I avoid social gatherings or speaking to new people because of fear of embarrassment.'),
(11, 'I relive a traumatic event through flashbacks or nightmares.'),
(12, 'I feel constantly on guard or easily startled.'),
(13, 'I feel emotionally numb or detached from others.'),
(14, 'I have unwanted thoughts that I can’t control.'),
(15, 'I feel compelled to perform certain behaviors or rituals to reduce anxiety.'),
(16, 'I often check things like locks or appliances multiple times.'),
(17, 'I have difficulty organizing tasks or belongings.'),
(18, 'I have trouble sitting still for long periods.'),
(19, 'I often act impulsively without thinking about the consequences.'),
(20, 'I have periods of time where I feel extremely energetic or "high" for days at a time.'),
(21, 'I sometimes go days with very little sleep but still have lots of energy.'),
(22, 'I hear voices or see things that others do not.'),
(23, 'I have beliefs that others say are strange or not true (e.g., being spied on).'),
(24, 'I restrict how much I eat because I’m afraid of gaining weight.'),
(25, 'I feel overweight even when others say I’m too thin.'),
(26, 'I often feel tired or have little energy.'),
(27, 'I have difficulty sleeping at night.'),
(28, 'I often feel irritable or get angry over small things.'),
(29, 'My thoughts race so fast that I have trouble keeping up with them.'),
(30, 'I have had times when I spent a lot of money or did risky things that were out of character for me.');
